### ISSUE TITLE
스프링 Property 설정 방법 변화 : InvalidConfigDataPropertyException: Property 'spring.profiles.include

### ISSUE THREAD

**Issue by gyureal** [gyureal/weGather#37]
## 에러 발생
`local`, `dev` Environment 를 나누고자 Property(`application.yml`)을 분리하려는데 아래 에러가 발생했습니다.

<img width="1237" alt="image" src="https://github.com/gyureal/weGather/assets/78974381/f3d7af61-7932-44b4-89cf-89d8c44f3b98">

```
org.springframework.boot.context.config.InvalidConfigDataPropertyException: Property 'spring.profiles.include' imported from location 'class path resource [application-local.yml]' is invalid in a profile specific resource [origin: class path resource [application-local.yml]
```

## 에러 원인
> 스프링 설정 방법 변화 : 스프링부트 2.4 부터 설정 정보를 등록하는 방식이 변화되었습니다.

## 해결
```yml
spring:
  profiles:
    group:
      local:
        - app
        - aws
        - db-local
      dev:
        - app
        - aws
        - db-dev
    active: local
```
## 참고
- https://theheydaze.tistory.com/512
- http://honeymon.io/tech/2021/01/16/spring-boot-config-data-migration.html
- https://1minute-before6pm.tistory.com/12
